import { useState } from "react";
import { supabase } from "../../supabaseClient";
import { supabaseService } from "../../services/supabaseService";
import { IconShieldCheck, IconCheckCircle, IconCopy } from "../Icons";

export default function DashboardDatabase({ onShowToast, onRefreshData }) {
  const [seeding, setSeeding] = useState(false);
  const [copied, setCopied] = useState(false);

  const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://psmzogadvxxuexdiavbq.supabase.co";
  const isClientReady = Boolean(supabase);

  const sqlSchema = `-- ==========================================
-- KARACHI BITES SUPABASE SQL SCHEMA
-- Run this in your Supabase SQL Editor:
-- ==========================================

-- 1. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  category TEXT NOT NULL,
  rating NUMERIC DEFAULT 4.8,
  image TEXT,
  badge TEXT,
  is_spicy BOOLEAN DEFAULT false,
  is_veg BOOLEAN DEFAULT false,
  prep_time TEXT,
  calories TEXT,
  ingredients JSONB DEFAULT '[]'::jsonb,
  addons JSONB DEFAULT '[]'::jsonb,
  in_stock BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT UNIQUE NOT NULL,
  customer_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT,
  area TEXT NOT NULL,
  address TEXT NOT NULL,
  delivery_notes TEXT,
  payment_method TEXT DEFAULT 'cod',
  status TEXT DEFAULT 'pending',
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal NUMERIC DEFAULT 0,
  delivery_fee NUMERIC DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  grand_total NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS email TEXT;

-- 3. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT,
  username TEXT NOT NULL,
  rating NUMERIC DEFAULT 5.0,
  review TEXT NOT NULL,
  avatar TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. ENABLE ROW LEVEL SECURITY & PUBLIC POLICIES (For Demo)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Products" ON public.products FOR SELECT USING (true);
CREATE POLICY "Public Write Products" ON public.products FOR ALL USING (true);

CREATE POLICY "Public Read Orders" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Public Insert Orders" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Orders" ON public.orders FOR UPDATE USING (true);

CREATE POLICY "Public Read Reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Public Insert Reviews" ON public.reviews FOR INSERT WITH CHECK (true);
`;

  const handleSeed = async () => {
    setSeeding(true);
    try {
      const count = await supabaseService.seedDefaultProducts();
      if (onShowToast) {
        onShowToast(`Successfully seeded ${count} dishes to Supabase & local cache! 🚀`);
      }
      if (onRefreshData) onRefreshData();
    } catch (err) {
      console.error(err);
      if (onShowToast) onShowToast("Seeding completed to local storage");
    } finally {
      setSeeding(false);
    }
  };

  const handleCopySql = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopied(true);
    if (onShowToast) onShowToast("SQL Schema copied to clipboard!");
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      {/* Top Card */}
      <div className="bg-white p-6 rounded-3xl border border-[#1C1715]/10 shadow-sm">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 pb-4 border-b border-[#1C1715]/10">
          <div>
            <div className="flex items-center gap-2">
              <span className="w-3 h-3 rounded-full bg-emerald-500 animate-ping" />
              <h2 className="font-display font-extrabold text-xl text-[#1C1715]">
                Supabase Backend & Database Sync
              </h2>
            </div>
            <p className="text-xs text-[#665C54] mt-0.5">
              Live database connectivity status and 1-click catalog deployment
            </p>
          </div>

          <button
            onClick={handleSeed}
            disabled={seeding}
            className="bg-[#E4572E] hover:bg-[#D1451C] text-white text-xs sm:text-sm font-extrabold px-5 py-3 rounded-2xl shadow-lg shadow-[#E4572E]/30 flex items-center gap-2 transition-all active:scale-95 disabled:opacity-50"
          >
            {seeding ? (
              <span>Seeding Menu to Supabase...</span>
            ) : (
              <>
                <span>🚀 1-Click Seed Menu to Supabase</span>
              </>
            )}
          </button>
        </div>

        {/* Status badges */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6">
          <div className="p-4 rounded-2xl bg-[#F7F2EB] flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center font-bold text-lg">
              ✓
            </div>
            <div>
              <p className="text-[10px] text-[#665C54] uppercase font-bold">Supabase Client</p>
              <p className="text-xs font-extrabold text-[#1C1715]">
                {isClientReady ? "Connected & Active" : "Offline Fallback Mode"}
              </p>
            </div>
          </div>

          <div className="p-4 rounded-2xl bg-[#F7F2EB] flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-100 text-blue-700 flex items-center justify-center font-bold text-lg">
              ⚡
            </div>
            <div>
              <p className="text-[10px] text-[#665C54] uppercase font-bold">Real-time Orders</p>
              <p className="text-xs font-extrabold text-[#1C1715]">
                PostgreSQL Channel Sync
              </p>
            </div>
          </div>

          <div className="p-4 rounded-2xl bg-[#F7F2EB] flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-100 text-amber-700 flex items-center justify-center font-bold text-lg">
              🛡️
            </div>
            <div>
              <p className="text-[10px] text-[#665C54] uppercase font-bold">Data Resilience</p>
              <p className="text-xs font-extrabold text-[#1C1715]">
                Dual Cloud + Local Storage
              </p>
            </div>
          </div>
        </div>

        <div className="mt-4 p-3 rounded-xl bg-gray-50 border border-gray-200 text-[11px] font-mono text-gray-700 break-all">
          <strong>Supabase Endpoint:</strong> {supabaseUrl}
        </div>
      </div>

      {/* SQL Migration Script Box */}
      <div className="bg-[#161311] text-white p-6 rounded-3xl shadow-xl space-y-4">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="font-display font-bold text-base text-white flex items-center gap-2">
              <IconShieldCheck className="w-5 h-5 text-[#E4572E]" /> Supabase SQL Schema (Copy & Run)
            </h3>
            <p className="text-xs text-white/60">
              Run this script in your Supabase SQL Editor if you want to initialize tables in a new project.
            </p>
          </div>

          <button
            onClick={handleCopySql}
            className="bg-white/10 hover:bg-white/20 text-white font-bold text-xs px-4 py-2 rounded-xl transition-colors flex items-center gap-1.5"
          >
            {copied ? <IconCheckCircle className="w-4 h-4 text-emerald-400" /> : <IconCopy className="w-4 h-4" />}
            <span>{copied ? "Copied!" : "Copy SQL Script"}</span>
          </button>
        </div>

        <pre className="p-4 rounded-2xl bg-[#231F1C] text-emerald-400 text-xs font-mono overflow-x-auto scroll-thin max-h-80 border border-white/10">
          {sqlSchema}
        </pre>
      </div>
    </div>
  );
}
